plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown
theme: minima

header_pages:
 - index.md
 - ata-aof.md
 - anadolu/index.md
 - auzef/index.md
